"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const transaction_controller_1 = require("../../controller/account/transaction.controller");
const express_1 = require("express");
const router = (0, express_1.Router)();
router.route('/credit').post(transaction_controller_1.creditAccount);
router.route('/credit/verify').post(transaction_controller_1.verifyCredit);
router.route('/debit').post(transaction_controller_1.debitAccount);
router.route('/debit/verify').post(transaction_controller_1.verifyDebit);
router.route('/:userId').get(transaction_controller_1.getAccountHistory);
exports.default = router;
